apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bym85s3lr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bym85s3lr-python 
  name: bym85s3lr-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bym85s3lr-python 
